version: '3.8'

services:
  prodsync:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prodsync-app
    ports:
      - "5001:5001"
    volumes:
      - ./server/data:/app/server/data
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=5001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --no-verbose --tries=1 --spider http://localhost:5001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # 可选：如果需要单独的数据库
  # db:
  #   image: sqlite:latest
  #   volumes:
  #     - ./data:/data
  #   restart: unless-stopped 